exec --no-startup-id slack 
exec --no-startup-id firefox
exec --no-startup-id /opt/cisco/anyconnect/bin/vpnui

assign [class="Slack"] $ws1
assign [class="firefox-aurora"] $ws3
assign [class="Code"] $ws2
assign [class="Com.cisco.anyconnect.gui"] $ws4
assign [class="Gnome-control-center"] $ws4

