# move focused workspace between monitors
bindsym $mod+Ctrl+greater move workspace to output right
bindsym $mod+Ctrl+less move workspace to output left

# switch between the current and the previously focused one
bindsym $mod+Mod1+w workspace back_and_forth

# Use mouse + mod to move floating window
floating_modifier $mod
